### DISCUSSION TITLE
CSS improvements

### DISCUSSION THREAD

**Discussion by nobodywasishere** [httpjamesm/AnonymousOverflow#162] [Show and tell]
I have some CSS improvements that I use locally that others may want to use as well. I found the syntax highlighting to sometimes break so I disabled it.

```css
:root {
    --main-bg: #161618;
    --meta-bg: #242424;
    --code-bg: #242424;
    line-height: 1.5;
}

.answer-meta.accepted {
  background-color: #4cd964 !important;
  color: black !important;
}

span {
    color: var(--text-color) !important;
    background-color: transparent;
}

pre {
    max-height: 300px; /* Set the maximum height */
    overflow-y: auto;  /* Enable vertical scrolling */
    line-height: 1.75;
}

@media (orientation: landscape) {
  .parent {
    max-width: 70%;
    width: fit-content;
  }
}
```

Current on left, my changes on right.
![image](https://github.com/user-attachments/assets/62359d95-c78c-442c-9776-8e1877eeabec)
