### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by vlnst** [httpjamesm/AnonymousOverflow#175]
# What's Happening?

Error: Received a non-OK status code 403 when trying to use AnonymousOverflow. It seems upstream started using CloudFlare and this is causing issues

## How to reproduce:
Go to any instances for example https://ao.bloat.cat/questions/799272/why-cant-one-ssl-certificate-be-used-for-multiple-machines or https://ao.maid.zone/questions/799272/why-cant-one-ssl-certificate-be-used-for-multiple-machines

**Comment by dave0003** [comment]
I'm also getting:

    Error: Received a non-OK status code 403

On 4 private instances in different countries (in US, Asia, Europe).

**Comment by httpjamesm** [comment]
Looks like Stack overflow doesn't want us 💔

**Comment by IAmChrisAMA** [comment]
It's most likely due to the Cloudflare challenge before loading the site. 
Maybe we can use FlareSolverr or similar software to bypass it...

**Comment by dave0003** [comment]
I can access stack overflow directly on the same connection without a cloudflare challenge, so I don't think that's generally the problem.

**Comment by ngn13** [comment]
I was able to get my instance working with FlareSolverr as @IAmChrisAMA suggested:
https://ao.ngn.tf/questions/799272/why-cant-one-ssl-certificate-be-used-for-multiple-machines

Please note that I did not thoroughly test this solution, use this only as a temporary solution, here are the instructions:
- Add FlareSolverr support to AnonymousOverflow, [here is my implementation](https://git.ngn.tf/ngn/anonymous_overflow/src/branch/custom/src/utils/request.go)
- Apply [this patch](https://github.com/FlareSolverr/FlareSolverr/pull/1272) to FlareSolverr
- If you are using docker, build the new images and place AnonymousOverflow and FlareSolverr in the same network so AnonymousOverflow can connect to FlareSolverr to get the solution for the cloudflare challenge

If you want an easier solution, you can use my images, here is an example compose file:
```yaml
services:
  anonymousoverflow:
    container_name: anonymous_overflow
    image: git.ngn.tf/ngn/anonymous_overflow:latest
    environment:
      APP_URL: "https://ao.example.com"
      JWT_SIGNING_SECRET: "topsecret"
      FLARESOLVER: "http://flaresolverr:8191"
      THEME: "dark"
    ports:
    - 8080:8080
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
    read_only: true
    restart: unless-stopped

  flaresolverr:
    container_name: anonymous_overflow_flaresolverr
    image: git.ngn.tf/ngn/flaresolverr:latest
    environment:
      LOG_LEVEL: "info"
      TZ: "Europe/Berlin"
      LANG: "en_US"
    security_opt:
    - no-new-privileges:true
    restart: unless-stopped
```

Again, **this is just temporary solution**

Also fuck cloudflare
