### ISSUE TITLE
GUIDE: How to fix "Error: Received a non-OK status code"

### ISSUE THREAD

**Issue by r2fo** [httpjamesm/AnonymousOverflow#86]
"Error: Received a non-OK status code" means that your instance is blocked by StackOverflow, to 'fix' this you can route the traffic of the AnonymousOverflow container over a VPN using GlueTun.

I couldn't find any straightforward guide so I wrote this one after a little bit of research, I opted for Cloudflare Warp since it's free and traffic is encrypted with HTTPS anyway. But you can use any of [these](https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers) providers, in that case you can skip to step 7 after adding your AnonymousOverflow ports to GlueTun's docker compose file.

1. Install wgcf
https://github.com/ViRb3/wgcf/blob/master/README.md (this tool generates a WireGuard config for Cloudflare WARP)

2. Run ```wgcf register``` and accept the terms and conditions of Cloudflare
3. Run ```wgcf generate``` to generate a WireGuard config (this will save to ```wgcf-profile.conf```)

Now we're gonna install GlueTun, it's a VPN client in the form of a Docker container. We need this to actually use the WireGuard config we generated

4. First create a folder for GlueTun
```mkdir gluetun```

5. Inside of that folder, create a docker compose file using ```nano docker-compose.yml``` and paste the following:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=
      - VPN_ENDPOINT_PORT=
      - WIREGUARD_PUBLIC_KEY=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESSES=
    ports:
      - '80:8080' #edit these
```

Modify the ports values to those that you use for AnonymousOverflow

Copy the values for ```VPN_ENDPOINT_PORT```, ```WIREGUARD_PUBLIC_KEY```, ```WIREGUARD_PRIVATE_KEY``` from the ```wgcf-profile.conf``` that we generated using  ```wgcf generate```

For ```VPN_ENDPOINT_IP```, you need to ping engage.cloudflareclient.com and use that IP address, for me it was 162.159.192.1

For ```WIREGUARD_ADDRESSES```, you only need to copy paste the IPv4 address (not the IPv6). For me it was 172.16.0.2/32

7. Now run ```docker compose up -d``` to start the GlueTun container and take note of the container name
8. Now edit the docker compose file of AnonymousOverflow and add the following line at the bottom so that all traffic gets send through the GlueTun container. Modify it with your GlueTun container's name and remove the parentheses

```
    network_mode: container:(name of the GlueTun container)
```

Remove the ports from AnonymousOverflow docker compose file, since we already added them to GlueTun's. The reason we did this is because Docker doesn't support setting a network_mode and publishing ports at the same time

And then finally run ```docker compose up -d``` to start AnonymousOverflow with the new settings

Sources: https://github.com/qdm12/gluetun/issues/1738, https://xtom.com/blog/how-to-route-your-docker-containers-through-a-vpn-gluetun-guide/#
